@echo off
@echo Running full Build Script, capturing output to buildlog.txt file...
build\lib\nant\0.91-alpha2\bin\nant.exe daily -f:Spring.VisualStudio.build > buildlog.txt
@echo Launching text file viewer to display buildlog.txt contents...
start "ignored but required placeholder window title argument" buildlog.txt