using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Spring.NET Visual Studio 2013 Extension 1.0.0")]
[assembly: AssemblyCompanyAttribute("http://www.springframework.net/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2004-2013 SpringSource")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.0; dev")]

