using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Spring.NET Visual Studio 2010 Extension (Daily build from 1/10/2011)")]
[assembly: AssemblyCompanyAttribute("http://www.springframework.net/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2004-2011 SpringSource")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.374")]
[assembly: AssemblyConfigurationAttribute("daily")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.374; daily")]

